<?php
/**
 * Guía pública: crear un administrador temporal de WordPress para CodePTY.
 */
?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class(array('codepty-guide-page', 'whatsapp-setup-guide', 'wordpress-access-guide')); ?>>
<?php wp_body_open(); ?><?php get_template_part('template-parts/site-header'); ?>
<main id="contenido">
<section class="guides-hero wa-guide-hero"><div class="container"><nav class="breadcrumbs" aria-label="Migas de pan"><a href="<?php echo esc_url(home_url('/')); ?>">Inicio</a><span aria-hidden="true">/</span><a href="<?php echo esc_url(home_url('/guias/')); ?>">Guías</a><span aria-hidden="true">/</span><span aria-current="page">Acceso a WordPress</span></nav><p class="eyebrow">Guía práctica · Acceso temporal</p><h1>Cómo dar acceso de administrador de WordPress a CodePTY</h1><p class="subtitle">Crea un usuario separado para que CodePTY pueda trabajar sin utilizar tu cuenta personal. Cuando termine el trabajo, podrás eliminarlo.</p><div class="wa-guide-meta"><span>Usuario independiente</span><span>Administrador temporal</span><span>Acceso eliminable</span></div></div></section>

<section class="wa-guide-section"><div class="container wa-guide-reading"><p class="eyebrow">Antes de comenzar</p><h2>No compartas tu usuario personal</h2><p>Entra con tu cuenta habitual de WordPress. Debes tener permisos de Administrador para crear otro usuario.</p><div class="wa-callout"><strong>Cuenta que debes crear</strong><p>Utiliza <code>codepty0@gmail.com</code> como correo del nuevo usuario. No envíes a CodePTY tu contraseña personal.</p></div></div></section>

<section class="wa-guide-section wa-guide-section--soft"><div class="container wa-guide-reading"><p class="eyebrow">Una acción en cada paso</p><h2>Crear el usuario de CodePTY</h2><ol class="wa-numbered"><li><span>1</span><div><h3>Entra en WordPress</h3><p>Abre <code>tudominio.com/wp-admin</code> e inicia sesión con tu propia cuenta.</p></div></li><li><span>2</span><div><h3>Abre «Usuarios»</h3><p>En el menú izquierdo, pulsa <strong>Usuarios</strong>.</p></div></li><li><span>3</span><div><h3>Pulsa «Añadir nuevo usuario»</h3><p>Abre la pantalla para crear una cuenta independiente.</p></div></li><li><span>4</span><div><h3>Escribe un nombre de usuario reconocible</h3><p>Por ejemplo, <code>codepty</code>. WordPress utilizará este nombre para iniciar sesión.</p></div></li><li><span>5</span><div><h3>Escribe el correo de CodePTY</h3><p>Introduce exactamente <code>codepty0@gmail.com</code>.</p></div></li><li><span>6</span><div><h3>Selecciona «Administrador»</h3><p>En el campo <strong>Perfil</strong> o <strong>Rol</strong>, selecciona <strong>Administrador</strong>.</p></div></li><li><span>7</span><div><h3>Envía el acceso de forma segura</h3><p>Utiliza la opción de WordPress para avisar al nuevo usuario por correo. Si no está disponible, acuerda con CodePTY un canal seguro; no envíes contraseñas en un mensaje público.</p></div></li><li><span>8</span><div><h3>Pulsa «Añadir nuevo usuario»</h3><p>Espera el mensaje de confirmación de WordPress.</p></div></li></ol><div class="guide-shot-placeholder" role="note"><strong>Captura real pendiente</strong><span>Pantalla «Usuarios → Añadir nuevo usuario» de la instalación real.</span></div></div></section>

<section class="wa-guide-section"><div class="container wa-guide-reading"><p class="eyebrow">Comprobación</p><h2>Confirma que la cuenta existe</h2><ol class="wa-numbered"><li><span>1</span><div><h3>Vuelve a «Usuarios»</h3><p>Abre la lista de usuarios instalados.</p></div></li><li><span>2</span><div><h3>Busca <code>codepty0@gmail.com</code></h3><p>Comprueba que aparece una sola vez.</p></div></li><li><span>3</span><div><h3>Revisa el perfil</h3><p>Debe indicar <strong>Administrador</strong>.</p></div></li><li><span>4</span><div><h3>Confirma con CodePTY</h3><p>CodePTY te indicará si ha recibido el aviso y puede entrar.</p></div></li></ol><div class="wa-callout wa-callout--warning"><strong>Si no puedes completar algún requisito</strong><p>La configuración quedará pendiente hasta que tu proveedor o soporte técnico te ayude a realizarlo.</p></div></div></section>

<section class="wa-guide-section wa-guide-section--dark"><div class="container wa-guide-reading"><p class="eyebrow">Cuando termine el trabajo</p><h2>Eliminar el acceso de CodePTY</h2><ol class="wa-numbered"><li><span>1</span><div><h3>Abre «Usuarios»</h3><p>Entra nuevamente con tu propia cuenta de Administrador.</p></div></li><li><span>2</span><div><h3>Localiza la cuenta de CodePTY</h3><p>Busca el usuario asociado a <code>codepty0@gmail.com</code>.</p></div></li><li><span>3</span><div><h3>Pulsa «Borrar» o «Eliminar»</h3><p>Confirma que has seleccionado únicamente la cuenta de CodePTY.</p></div></li><li><span>4</span><div><h3>Conserva el contenido existente</h3><p>Si WordPress pregunta por contenido creado por ese usuario, asígnalo a tu cuenta de Administrador en lugar de eliminarlo.</p></div></li><li><span>5</span><div><h3>Comprueba la lista</h3><p>Verifica que <code>codepty0@gmail.com</code> ya no aparece y que tu propia cuenta continúa funcionando.</p></div></li></ol></div></section>
</main>
<?php get_template_part('template-parts/site-footer'); ?><?php wp_footer(); ?>
</body></html>
