<?php
/**
 * Guía pública: configurar una página de empresa en Facebook.
 */
?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class(array('codepty-guide-page', 'whatsapp-setup-guide', 'facebook-setup-guide')); ?>><?php wp_body_open(); get_template_part('template-parts/site-header'); ?>
<main id="contenido">
<section class="guides-hero wa-guide-hero"><div class="container"><nav class="breadcrumbs" aria-label="Migas de pan"><a href="<?php echo esc_url(home_url('/')); ?>">Inicio</a><span aria-hidden="true">/</span><a href="<?php echo esc_url(home_url('/guias/')); ?>">Guías</a><span aria-hidden="true">/</span><span aria-current="page">Facebook</span></nav><p class="eyebrow">Guía práctica · Presencia empresarial</p><h1>Cómo crear y cuidar la página de Facebook de tu negocio</h1><p class="subtitle">Qué tipo de cuenta necesitas, qué imágenes y datos preparar, cómo proteger el acceso y qué publicar para mantener una presencia útil y creíble.</p><div class="wa-guide-meta"><span>Tiempo inicial: 45–90 minutos</span><span>Necesitas un perfil personal real</span><span>La Página pertenece al negocio</span></div></div></section>

<nav class="wa-guide-index" aria-label="Contenido de la guía"><div class="container"><strong>Ir a:</strong><a href="#tipo">Tipo de cuenta</a><a href="#crear">Crear</a><a href="#imagenes">Imágenes</a><a href="#datos">Datos</a><a href="#seguridad">Seguridad</a><a href="#publicaciones">Publicar</a><a href="#comprobacion">Comprobar</a></div></nav>

<section class="wa-guide-section" id="tipo"><div class="container wa-guide-reading"><p class="eyebrow">La decisión fundamental</p><h2>Crea una Página para el negocio</h2><p>La persona propietaria utiliza su perfil personal auténtico para crear y administrar una <strong>Página de Facebook</strong>. Los clientes siguen la Página y la información privada del propietario permanece separada de la actividad comercial.</p>
<div class="fb-account-grid"><article class="fb-account-card fb-account-card--correct"><span>Recomendado</span><h3>Página</h3><p>Para negocios, marcas y organizaciones. Permite información comercial, botón de acción, estadísticas, publicidad y acceso de varias personas.</p></article><article class="fb-account-card"><span>Acceso personal</span><h3>Perfil personal</h3><p>Representa a una persona real y sirve para crear y administrar la Página. Utiliza el perfil auténtico del propietario.</p></article><article class="fb-account-card"><span>Para comunidades</span><h3>Grupo</h3><p>Sirve para conversaciones entre miembros y puede complementar a la Página cuando el negocio necesita una comunidad.</p></article><article class="fb-account-card"><span>Para creadores</span><h3>Modo profesional</h3><p>Añade herramientas públicas a un perfil personal. La Página ofrece una separación más clara entre la empresa y la identidad de su propietario.</p></article></div>
<div class="wa-callout"><strong>La Página reúne seguidores del negocio</strong><p>El perfil personal y la Página son activos diferentes. Publica como Página cuando hables en nombre del negocio y como persona cuando corresponda.</p></div></div></section>

<section class="wa-guide-section wa-guide-section--soft" id="crear"><div class="container wa-guide-reading"><p class="eyebrow">Creación inicial</p><h2>Crea la Página con información real</h2><ol class="wa-numbered"><li><span>1</span><div><h3>Entra desde el perfil del propietario</h3><p>Abre Páginas → Crear nueva Página. El propietario debe conservar acceso y métodos de recuperación propios.</p></div></li><li><span>2</span><div><h3>Escribe el nombre comercial exacto</h3><p>Usa el mismo nombre que aparece en la web, local, facturas y otras redes. Reserva las frases promocionales para la presentación y las publicaciones.</p></div></li><li><span>3</span><div><h3>Elige la categoría más precisa</h3><p>Selecciona la actividad principal y añade categorías complementarias únicamente si describen servicios reales.</p></div></li><li><span>4</span><div><h3>Redacta una presentación breve</h3><p>Explica qué hace el negocio, a quién atiende y en qué zona. Después podrás completar todos los datos.</p></div></li><li><span>5</span><div><h3>Crea un nombre de usuario</h3><p>Elige un identificador corto, reconocible y coherente con Instagram cuando esté disponible.</p></div></li></ol>
<div class="fb-screen" role="img" aria-label="Ilustración del formulario para crear una página de Facebook"><div class="fb-screen__bar">Crear una página</div><div class="fb-screen__body"><div><small>Nombre de la página</small><span>Nombre del negocio</span></div><div><small>Categoría</small><span>Actividad principal</span></div><div><small>Presentación</small><span>Qué hacemos · Para quién · Zona</span></div><b>Crear página</b></div></div></div></section>

<section class="wa-guide-section" id="imagenes"><div class="container wa-guide-reading"><p class="eyebrow">Material visual</p><h2>Qué imágenes necesitamos y para qué sirven</h2><p>Las medidas de Facebook pueden cambiar y la plataforma adapta las imágenes a cada pantalla. Guarda siempre los originales en alta calidad y comprueba el resultado en móvil y computadora.</p>
<div class="fb-image-grid"><article><div class="fb-image-demo fb-image-demo--avatar"><span>LOGO</span></div><h3>Foto de perfil</h3><strong>Aporta: 640 × 640 px</strong><p>Meta indica 320 × 320 px para buena calidad; pedimos un original mayor para poder prepararlo. Debe ser cuadrado, PNG si lleva logotipo o texto, y funcionar recortado como círculo.</p><small>Objetivo: reconocer al negocio en publicaciones, comentarios y búsquedas.</small></article><article><div class="fb-image-demo fb-image-demo--cover"><span>Zona segura para texto y sujeto</span></div><h3>Foto de portada</h3><strong>Aporta: 1640 × 624 px</strong><p>Equivale al doble del formato rápido de 820/851 × 312/315. Meta la adapta y puede tapar parte del lado izquierdo con el perfil. JPG sRGB para fotografía; PNG para logotipo o texto.</p><small>Objetivo: explicar actividad, producto, espacio o propuesta de un vistazo.</small></article><article><div class="fb-image-demo fb-image-demo--square"><span>1:1</span></div><h3>Publicación cuadrada</h3><strong>Aporta: 1080 × 1080 px</strong><p>Formato versátil para trabajos, productos, avisos y testimonios autorizados. Mantén poco texto dentro de la imagen.</p><small>Objetivo: comunicar una idea clara en el feed.</small></article><article><div class="fb-image-demo fb-image-demo--portrait"><span>4:5</span></div><h3>Publicación vertical</h3><strong>Aporta: 1080 × 1350 px</strong><p>Aprovecha mejor la pantalla del teléfono para fotografías de trabajos, equipo, producto o proceso.</p><small>Objetivo: dar protagonismo visual con lectura cómoda.</small></article><article><div class="fb-image-demo fb-image-demo--story"><span>9:16</span></div><h3>Historias y reels</h3><strong>Aporta: 1080 × 1920 px</strong><p>Deja márgenes arriba y abajo para mantener textos, logotipos y llamadas a la acción dentro del área visible.</p><small>Objetivo: contenido vertical breve, cercano y actual.</small></article></div>
<div class="wa-callout wa-callout--warning"><strong>Utiliza imágenes propias o con licencia verificable</strong><p>Confirma también la autorización de las personas y espacios que aparecen. Protege la privacidad de clientes y menores, y mantén fuera de la imagen matrículas, documentos y conversaciones.</p></div></div></section>

<section class="wa-guide-section wa-guide-section--dark" id="datos"><div class="container wa-guide-reading"><p class="eyebrow">Perfil completo</p><h2>Qué información debe explicar la Página</h2><div class="fb-profile-layout"><div><ul class="fb-data-list"><li><strong>Presentación:</strong> actividad principal en una frase.</li><li><strong>Descripción:</strong> qué haces, para quién, zona, especialidad y forma de trabajar.</li><li><strong>Web:</strong> página oficial del negocio.</li><li><strong>WhatsApp y teléfono:</strong> números comerciales probados.</li><li><strong>Instagram:</strong> conecta la cuenta profesional si se utiliza.</li><li><strong>Linktree:</strong> úsalo si reúne destinos útiles; prioriza la web como referencia principal.</li><li><strong>Correo:</strong> dirección comercial atendida.</li><li><strong>Dirección o área de servicio:</strong> publica solo lo necesario.</li><li><strong>Horario:</strong> atención normal y cambios festivos.</li><li><strong>Servicios:</strong> lista concreta y comprensible.</li><li><strong>Botón:</strong> WhatsApp, llamar, reservar, comprar o visitar la web según el objetivo real.</li></ul></div><div class="fb-page-map" role="img" aria-label="Esquema de una página empresarial completa"><div class="fb-page-map__cover">Portada: qué hace el negocio</div><div class="fb-page-map__identity"><span>LOGO</span><div><strong>Nombre del negocio</strong><small>@usuario · categoría</small></div></div><div class="fb-page-map__button">Enviar mensaje / WhatsApp</div><div class="fb-page-map__info"><span>Descripción</span><span>Web</span><span>Horario</span><span>Ubicación</span><span>Servicios</span></div></div></div>
<div class="wa-callout"><strong>Una descripción útil responde cuatro preguntas</strong><p>¿Qué ofrece el negocio? ¿A quién ayuda? ¿Dónde trabaja? ¿Cuál es el siguiente paso? Prioriza información concreta y verificable frente a frases genéricas como “somos los mejores”.</p></div></div></section>

<section class="wa-guide-section" id="seguridad"><div class="container wa-guide-reading"><p class="eyebrow">Propiedad y permisos</p><h2>Protege la Página y asigna cada acceso con precisión</h2><div class="wa-security-grid"><article><h3>Dos propietarios con control total</h3><p>Configura dos personas responsables y de máxima confianza dentro del negocio con acceso de Facebook y control total. Si uno de los perfiles queda bloqueado por varios intentos de acceso, entra en revisión o pierde temporalmente su método de recuperación, el segundo mantiene operativa la Página y puede gestionar de nuevo su acceso cuando corresponda.</p></article><article><h3>Autenticación en dos pasos</h3><p>Actívala en ambas personas y en todo el equipo con acceso. Cada propietario conserva sus propios métodos de recuperación, correo y teléfono actualizados.</p></article><article><h3>Continuidad y recuperación</h3><p>El segundo propietario puede devolver o gestionar el acceso a la Página. El desbloqueo del perfil personal afectado se completa mediante las herramientas de recuperación de Meta.</p></article><article><h3>Control total: para propietarios</h3><p>Quien tiene control total puede cambiar ajustes y accesos, retirar incluso al otro propietario o eliminar la Página. Asígnalo únicamente a esas dos personas responsables.</p></article><article><h3>Acceso parcial o por tareas</h3><p>Asigna los permisos necesarios para contenido, mensajes, comentarios, anuncios o estadísticas. Para la mayoría de tareas de CodePTY basta un acceso específico y temporal.</p></article><article><h3>Accesos individuales</h3><p>Cada colaborador utiliza su propio perfil y recibe permisos personales. Al terminar una relación laboral, actualiza inmediatamente la lista de accesos.</p></article><article><h3>Revisión periódica</h3><p>Comprueba accesos, sesiones, cuentas conectadas, métodos de pago y notificaciones de seguridad al menos cada trimestre.</p></article></div>
<h3 class="fb-subheading">Quién puede publicar, responder y moderar</h3><div class="fb-permission-table"><div><strong>Propietarios</strong><span>Control total y recuperación</span><small>Dos personas responsables</small></div><div><strong>Contenido</strong><span>Crear y programar publicaciones</span><small>Personal o proveedor encargado</small></div><div><strong>Mensajes y comentarios</strong><span>Responder, ocultar o reportar</span><small>Equipo de atención con protocolo</small></div><div><strong>Anuncios</strong><span>Campañas y presupuesto</span><small>Solo quien gestione publicidad</small></div><div><strong>Estadísticas</strong><span>Consultar resultados</span><small>Acceso de lectura cuando baste</small></div></div>
<div class="wa-callout wa-callout--warning"><strong>Si pierdes acceso o sospechas un ataque</strong><p>Actúa desde un dispositivo habitual: cambia la contraseña del perfil afectado, cierra sesiones desconocidas, revisa correos de Meta, comprueba accesos de la Página y utiliza exclusivamente la recuperación oficial para cuentas o Páginas comprometidas.</p></div></div></section>

<section class="wa-guide-section wa-guide-section--soft"><div class="container wa-guide-reading"><p class="eyebrow">Comunidad y moderación</p><h2>Decide qué pueden publicar otras personas</h2><div class="fb-moderation-grid"><article><h3>Publicaciones de visitantes</h3><p>Actívalas cuando exista una persona responsable de revisarlas. Si aportan valor, modéralas y establece reglas claras.</p></article><article><h3>Comentarios</h3><p>Responde preguntas reales, corrige errores con calma y aplica las herramientas de moderación al spam, estafas, datos privados, insultos o contenido ilegal.</p></article><article><h3>Mensajes</h3><p>Define quién responde, en qué horario, qué información puede pedir y cuándo debe trasladar una consulta al responsable.</p></article><article><h3>Filtros y palabras</h3><p>Utiliza las herramientas de moderación disponibles y revisa sus decisiones para mantener visibles las consultas legítimas.</p></article></div><p class="fb-policy-note"><strong>Regla sencilla:</strong> crítica legítima se responde; datos personales se protegen; spam y fraude se moderan; amenazas o contenido ilegal se documentan y reportan.</p></div></section>

<section class="wa-guide-section" id="publicaciones"><div class="container wa-guide-reading"><p class="eyebrow">Actividad sostenible</p><h2>Qué publicar y con qué frecuencia</h2><p>Cada negocio necesita su propio ritmo. Para muchos pequeños negocios, empezar con <strong>una o dos publicaciones útiles por semana</strong> y mantener la información actualizada resulta sostenible. Ajusta la frecuencia con datos reales de alcance, interacción y consultas.</p>
<div class="fb-content-grid"><article><span>01</span><h3>Trabajos y resultados</h3><p>Antes y después, proyectos terminados o casos explicados con autorización.</p></article><article><span>02</span><h3>Productos y servicios</h3><p>Qué resuelven, para quién sirven, condiciones y cómo consultar.</p></article><article><span>03</span><h3>Proceso y equipo</h3><p>Cómo trabajáis, instalaciones, herramientas y personas que dan confianza.</p></article><article><span>04</span><h3>Consejos útiles</h3><p>Respuestas a dudas frecuentes sin convertir cada publicación en un anuncio.</p></article><article><span>05</span><h3>Información práctica</h3><p>Horario especial, disponibilidad, ubicación, eventos o cambios importantes.</p></article><article><span>06</span><h3>Pruebas sociales reales</h3><p>Opiniones y colaboraciones verificables, siempre con permiso.</p></article></div>
<div class="fb-week"><strong>Ejemplo sencillo de un mes</strong><span>Semana 1 · Servicio destacado</span><span>Semana 2 · Trabajo real</span><span>Semana 3 · Consejo frecuente</span><span>Semana 4 · Equipo, proceso o novedad</span></div>
<h3 class="fb-subheading">A quién seguir e interactuar</h3><ul class="service-checklist"><li>Clientes y colaboradores únicamente cuando la relación sea pública y apropiada.</li><li>Proveedores, asociaciones y cámaras empresariales relevantes.</li><li>Entidades locales, comunidad y eventos de la zona.</li><li>Fuentes profesionales fiables de tu sector.</li><li>Negocios complementarios con los que exista una relación real.</li></ul><p>Construye una audiencia auténtica mediante relaciones relevantes, contenido útil e interacciones personales. Comenta como Página cuando puedas aportar información concreta a la conversación.</p></div></section>

<section class="wa-guide-section wa-guide-section--dark" id="comprobacion"><div class="container wa-guide-reading"><p class="eyebrow">Antes de entregar</p><h2>Lista final de comprobación</h2><div class="final-checklist wa-final-checklist"><label><input type="checkbox">Es una Página oficial creada desde el perfil auténtico del propietario.</label><label><input type="checkbox">Dos propietarios responsables conservan control total y métodos de recuperación independientes.</label><label><input type="checkbox">Ambos propietarios han comprobado que pueden acceder y gestionar los accesos de la Página.</label><label><input type="checkbox">Nombre, usuario, categoría y descripción son correctos.</label><label><input type="checkbox">Perfil y portada se ven bien en móvil y computadora.</label><label><input type="checkbox">Web, WhatsApp, Instagram, Linktree, correo y teléfono están probados.</label><label><input type="checkbox">Horario, dirección o zona y servicios están actualizados.</label><label><input type="checkbox">El botón principal conduce a la acción correcta.</label><label><input type="checkbox">Cada persona tiene el acceso necesario y 2FA activo.</label><label><input type="checkbox">Publicaciones de visitantes, mensajes y comentarios tienen responsable.</label><label><input type="checkbox">Existe un ritmo de publicación que el negocio puede mantener.</label></div><div class="wa-share"><h3>Qué debes enviar a CodePTY</h3><p>Comparte la URL de la Página, nombre de usuario, logotipo original, portada o fotografías disponibles, datos comerciales confirmados y la invitación de acceso acordada.</p><p><strong>Conserva en privado tu contraseña y tus códigos de autenticación y recuperación.</strong></p></div></div></section>

<section class="wa-guide-section"><div class="container wa-guide-reading"><p class="eyebrow">Dudas habituales</p><h2>Preguntas frecuentes</h2><div class="faq-list wa-guide-faq"><details><summary>¿Qué usuario personal se utiliza para crear el negocio?</summary><p>Utiliza el perfil real del propietario para crear la Página y concede accesos individuales a las demás personas.</p></details><details><summary>¿Qué acceso necesita CodePTY?</summary><p>El permiso debe corresponder a la tarea y al tiempo acordado. El propietario conserva siempre el control del activo.</p></details><details><summary>¿Página, grupo o modo profesional?</summary><p>Para presentar un negocio, la base es una Página. Un grupo puede complementar una comunidad y el modo profesional está orientado a la actividad pública de una persona.</p></details><details><summary>¿Cómo se relacionan los clientes con la Página?</summary><p>Los clientes pueden seguir la Página mientras la vida personal del propietario permanece separada.</p></details><details><summary>¿Con qué frecuencia conviene publicar?</summary><p>Una frecuencia sostenible de contenido útil y datos actualizados aporta más valor que publicar por obligación. Empieza con una o dos publicaciones semanales y evalúa.</p></details><details><summary>¿Puedo publicar la misma pieza en Facebook e Instagram?</summary><p>Puede compartirse cuando encaja, revisando formato, texto, enlaces y contexto. Las plataformas deben ser coherentes y pueden adaptar cada pieza a su uso.</p></details></div></div></section>
</main><?php get_template_part('template-parts/site-footer'); wp_footer(); ?></body></html>
