<?php
/**
 * Contenido principal de la página Más contactos.
 */
?>
<section class="service-section contacts-entry" id="puntos-de-entrada">
    <div class="container trust-split">
        <div class="trust-copy"><p class="eyebrow">Varias puertas, un mismo negocio</p><h2>Tus clientes no empiezan todos por el mismo sitio</h2><p>Una persona puede buscar una solución concreta en Google. Otra puede ver un trabajo en Instagram, leer un comentario en Facebook, recibir un enlace por recomendación o entrar directamente en tu página web.</p><p>Una presencia digital distribuida ofrece varios puntos de entrada y permite que cada persona siga el camino que le resulte natural. Los canales se apoyan entre sí: uno llama la atención, otro aporta información y otro facilita la conversación.</p></div>
        <div class="contacts-funnel" aria-label="Diferencia entre visibilidad, visitas, contactos y resultados comerciales"><div><strong>1</strong><span>Apariciones</span><small>El negocio se muestra</small></div><div><strong>2</strong><span>Visitas</span><small>Alguien decide saber más</small></div><div><strong>3</strong><span>Contactos</span><small>Empieza una conversación</small></div><div><strong>4</strong><span>Clientes</span><small>Algunos contactos contratan</small></div><div><strong>5</strong><span>Ventas</span><small>El resultado depende del proceso comercial</small></div></div>
    </div>
</section>

<section class="service-section service-section--soft contacts-channels" id="canales">
    <div class="container"><div class="trust-section-heading"><p class="eyebrow">Funciones diferentes, objetivos conectados</p><h2>Cada plataforma puede producir un tipo distinto de contacto</h2><p>No existe un canal universalmente mejor. Su utilidad depende de qué busca el cliente, del tipo de negocio y del momento en que se encuentra.</p></div>
        <article class="trust-platform trust-platform--featured"><span class="trust-platform__number">01</span><div><h3>Página web: información completa y un destino propio</h3><p>Explica servicios, argumentos, zonas de trabajo, preguntas frecuentes y formas de contacto. Puede recibir tráfico de Google, redes, anuncios, enlaces compartidos y perfiles externos.</p></div><a class="trust-platform__role" href="<?php echo esc_url(home_url('/pagina-web-para-tu-negocio-en-panama/')); ?>">Ver la oferta de página web</a></article>
        <div class="trust-platform-grid">
            <article class="trust-platform"><span class="trust-platform__number">02</span><h3>Google: una necesidad concreta</h3><p>Conecta con búsquedas por servicio, ubicación, horario o reputación. Desde un resultado, la persona puede abrir la web, llamar, pedir indicaciones o consultar el perfil del negocio.</p></article>
            <article class="trust-platform"><span class="trust-platform__number">03</span><h3>Facebook: comunidad y cercanía</h3><p>La actividad, los comentarios y las novedades permiten descubrir el negocio. Hay clientes que se sienten más cómodos aquí que en Instagram.</p></article>
            <article class="trust-platform"><span class="trust-platform__number">04</span><h3>Instagram: descubrimiento visual</h3><p>Trabajos, productos y resultados ayudan a entender visualmente la oferta. Aunque no publiques con la misma frecuencia, conviene reservar el usuario, completar el perfil y vincularlo: determinadas configuraciones de Meta pueden requerir una cuenta profesional de Instagram.</p></article>
            <article class="trust-platform"><span class="trust-platform__number">05</span><h3>Linktree o enlace central: acceso rápido</h3><p>Reúne los destinos principales para que cada persona pueda elegir entre la web, WhatsApp, redes, catálogo, reservas u otros recursos.</p></article>
            <article class="trust-platform"><span class="trust-platform__number">06</span><h3>WhatsApp: conversación directa</h3><p>Reduce la fricción para quien quiere hacer una pregunta breve, enviar una fotografía, consultar disponibilidad o iniciar una conversación comercial.</p></article>
            <article class="trust-platform"><span class="trust-platform__number">07</span><h3>Llamadas y formularios: preferencias distintas</h3><p>La llamada resulta inmediata para algunas personas; el formulario permite explicar una necesidad con calma y deja una consulta ordenada para responder después.</p></article>
        </div>
        <div class="contacts-ads-note"><strong>También puedes ampliar el alcance con publicidad localizada.</strong><p>Las campañas SEM en Google pueden mostrar el negocio ante búsquedas concretas, mientras que Facebook e Instagram permiten dirigir anuncios a públicos de determinadas ubicaciones. La campaña debe conducir hacia una web, WhatsApp, formulario u otro destino claro donde la persona pueda contactar.</p></div>
    </div>
</section>

<section class="service-section contacts-journey-section" id="recorrido">
    <div class="container"><div class="trust-section-heading"><p class="eyebrow">Un recorrido sencillo</p><h2>De una aparición a una conversación</h2><p>El contacto suele llegar después de varias comprobaciones, incluso cuando el recorrido completo dura pocos minutos.</p></div>
        <ol class="trust-journey contacts-journey"><li><span>1</span><div><h3>Descubre</h3><p>Encuentra el negocio en un resultado, publicación, anuncio o recomendación.</p></div></li><li><span>2</span><div><h3>Consulta</h3><p>Abre la web, Google o algún perfil social.</p></div></li><li><span>3</span><div><h3>Comprueba</h3><p>Busca señales de que el negocio es real y está activo.</p></div></li><li><span>4</span><div><h3>Entiende</h3><p>Confirma qué ofrece y si puede resolver su necesidad.</p></div></li><li><span>5</span><div><h3>Elige</h3><p>Encuentra WhatsApp, teléfono, formulario u otra vía cómoda.</p></div></li><li><span>6</span><div><h3>Contacta</h3><p>Da el primer paso e inicia una conversación.</p></div></li></ol>
        <blockquote class="trust-statement trust-statement--blue">Más visibilidad crea oportunidades de visita. Una presencia clara y coherente ayuda a convertir algunas de esas visitas en contactos.</blockquote>
    </div>
</section>

<section class="service-section service-section--dark contacts-readiness" id="intencion">
    <div class="container trust-split"><div class="trust-copy"><p class="eyebrow">Personas en momentos diferentes</p><h2>No todo contacto llega preparado para comprar</h2><p>Algunas personas preguntan precios; otras comparan opciones, quieren resolver una duda o todavía están definiendo lo que necesitan. También hay quien ya busca contratar, reservar o hacer un encargo.</p><p>La presencia digital debe facilitar ese primer paso sin exigir una decisión inmediata. Una conversación bien atendida puede aclarar necesidades y mostrar si existe un buen encaje.</p></div><div class="contacts-intents"><span>Preguntar</span><span>Comparar</span><span>Informarse</span><span>Confirmar disponibilidad</span><span>Pedir presupuesto</span><span>Contratar o reservar</span></div></div>
</section>

<section class="service-section contacts-methods" id="formas-de-contacto">
    <div class="container trust-split"><div class="trust-copy"><p class="eyebrow">Menos fricción</p><h2>Más formas de contactar significan menos oportunidades perdidas</h2><p>No todos los clientes quieren utilizar el mismo medio. Mostrar opciones claras evita obligar a una persona a buscar un teléfono, registrarse en una plataforma que no usa o abandonar porque no encuentra cómo preguntar.</p></div><ul class="contacts-method-list"><li><strong>WhatsApp</strong><span>Para conversaciones directas y sencillas.</span></li><li><strong>Llamada telefónica</strong><span>Para quien prefiere hablar en el momento.</span></li><li><strong>Formulario</strong><span>Para consultas detalladas o fuera de horario.</span></li><li><strong>Redes sociales</strong><span>Para responder donde ocurrió el descubrimiento.</span></li><li><strong>Ubicación e indicaciones</strong><span>Cuando el negocio recibe visitas presenciales.</span></li></ul></div>
</section>

<section class="service-section service-section--soft contacts-coherence" id="coherencia">
    <div class="container trust-split"><div class="trust-copy"><p class="eyebrow">Contactos con expectativas más claras</p><h2>La coherencia mejora la calidad de los contactos</h2><p>Cuando la web, Google, Facebook e Instagram muestran el mismo negocio, los mismos servicios y datos compatibles, la persona entiende mejor qué puede esperar antes de escribir.</p><p>La coherencia no garantiza una contratación, pero reduce confusiones y ayuda a que las consultas lleguen mejor orientadas. Puedes ver con más detalle cómo construimos <a href="<?php echo esc_url(home_url('/mas-confianza/')); ?>">más confianza para tu negocio</a>.</p></div><div class="trust-search"><div class="trust-search__bar"><span aria-hidden="true"></span><strong>Señales que deben coincidir</strong></div><ul><li><span>01</span>Nombre e identidad</li><li><span>02</span>Servicios y propuesta</li><li><span>03</span>Teléfono y WhatsApp</li><li><span>04</span>Horarios y ubicación</li><li><span>05</span>Enlaces y llamadas a la acción</li></ul></div></div>
</section>

<section class="service-section contacts-codepty" id="que-hacemos">
    <div class="container"><div class="trust-section-heading"><p class="eyebrow">Una presencia conectada</p><h2>Qué hacemos en CodePTY para facilitar esos contactos</h2><p>Organizamos los canales para que no parezcan piezas aisladas y colocamos rutas claras desde el descubrimiento hasta la conversación.</p></div><div class="contacts-work-grid"><article><span>01</span><h3>Definimos el centro</h3><p>Preparamos una <a href="<?php echo esc_url(home_url('/pagina-web-para-tu-negocio-en-panama/')); ?>">página web para tu negocio en Panamá</a> que explica la oferta y reúne los destinos importantes.</p></article><article><span>02</span><h3>Conectamos los canales</h3><p>Enlazamos web, Google, Facebook, Instagram, WhatsApp y otros recursos relevantes para que el usuario pueda continuar su recorrido.</p></article><article><span>03</span><h3>Hacemos visible el siguiente paso</h3><p>Situamos llamadas a la acción hacia WhatsApp, teléfono o formulario donde resultan útiles, incluida una <a href="<?php echo esc_url(home_url('/pagina-web-con-whatsapp/')); ?>">conexión clara entre web y WhatsApp</a>.</p></article></div><p class="trust-note">Empezamos por los canales que tengan sentido para el negocio. La gestión continuada de perfiles, contenidos o campañas se acuerda por separado cuando sea necesaria.</p></div>
</section>

<section class="service-section service-section--soft trust-faq" id="preguntas">
    <div class="container faq-grid service-faq"><div class="faq-heading"><p class="eyebrow">Dudas frecuentes</p><h2>Preguntas sobre cómo conseguir más contactos</h2><p>Respuestas realistas para construir una presencia digital útil sin promesas automáticas.</p></div><div class="faq-list">
        <details><summary>¿Tener más redes sociales garantiza más clientes?</summary><p>No. Más canales pueden aumentar las oportunidades de ser descubierto y contactado, pero los resultados también dependen de la oferta, el mercado, la atención y el proceso comercial.</p></details>
        <details><summary>¿Necesito estar en todas las plataformas?</summary><p>No. Conviene elegir los canales que usan tus posibles clientes y que el negocio pueda mantener con información correcta. Es mejor una presencia útil y coherente que muchos perfiles abandonados.</p></details>
        <details><summary>¿Qué canal suele generar más contactos?</summary><p>No hay una respuesta igual para todos. Google puede ser importante para necesidades concretas; Instagram para trabajos visuales; Facebook para comunidad; y la web para explicar y organizar la oferta. Hay que observar el comportamiento real de cada negocio.</p></details>
        <details><summary>¿Es mejor WhatsApp o un formulario?</summary><p>Se complementan. WhatsApp facilita una conversación inmediata; el formulario permite enviar una consulta ordenada, detallada o fuera de horario. Ofrecer ambos evita imponer una sola preferencia.</p></details>
        <details><summary>¿Para qué necesito una web si ya tengo Facebook o Instagram?</summary><p>La web es un espacio propio para presentar la información completa, organizar servicios y conectar todos los canales. Las redes ayudan a descubrir y mostrar actividad, pero no sustituyen esa referencia central.</p></details>
        <details><summary>¿Cómo se conectan todos los canales?</summary><p>Mediante enlaces claros y datos coincidentes: los perfiles apuntan a la web o al enlace central, la web ofrece WhatsApp, teléfono y formulario, y cada plataforma ayuda a continuar hacia el siguiente paso.</p></details>
        <details><summary>¿Puedo aumentar los contactos mediante campañas publicitarias?</summary><p>Sí, las campañas SEM en Google y los anuncios localizados en Facebook o Instagram pueden aumentar la visibilidad ante públicos relevantes y generar más oportunidades de contacto. No garantizan un número concreto de consultas: el resultado depende de la oferta, la segmentación, el presupuesto, la competencia, el anuncio y la facilidad para contactar.</p></details>
        <details><summary>¿Qué ocurre si todavía no tengo perfiles profesionales?</summary><p>Podemos revisar qué canales son útiles y preparar una base coherente según el alcance acordado. No es necesario abrir perfiles sin una función clara.</p></details>
        <details><summary>¿Puedo empezar con pocos canales y añadir otros después?</summary><p>Sí. Se puede empezar con una web y los medios de contacto prioritarios, y añadir perfiles o destinos cuando el negocio tenga contenido, recursos y una razón para utilizarlos.</p></details>
    </div></div>
</section>

<section class="closing trust-closing contacts-closing" id="contactar"><div class="container"><div class="closing-box"><div><p class="eyebrow">Haz más fácil el primer paso</p><h2>Convierte tus canales en caminos hacia una conversación</h2><p>Cuéntanos cómo encuentran hoy tus clientes el negocio y revisaremos qué presencia digital puede ayudarte a recibir consultas desde más lugares.</p></div><div class="closing-actions"><a class="button light" href="#consulta">Quiero mejorar mis puntos de contacto</a></div></div></div></section>
