<?php
/** Plantilla compartida para una página comercial autónoma. */
$all_services = codepty_service_landings();
$service = $all_services[$codepty_service_key] ?? null;
if (!$service) { return; }
?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class(array('codepty-service-detail', 'service-landing', 'service-' . $codepty_service_key)); ?>><?php wp_body_open(); get_template_part('template-parts/site-header'); ?>
<main id="contenido">
<section class="sl-hero"><div class="container">
  <nav class="breadcrumbs sl-breadcrumbs" aria-label="Migas de pan"><a href="<?php echo esc_url(home_url('/')); ?>">Inicio</a><span aria-hidden="true">/</span><span aria-current="page"><?php echo esc_html($service['crumb']); ?></span></nav>
  <div class="sl-hero__grid">
  <div class="sl-hero__main"><p class="eyebrow"><?php echo esc_html($service['eyebrow']); ?></p><h1><?php echo esc_html($service['title']); ?></h1><p class="subtitle"><?php echo esc_html($service['intro']); ?></p>
  <ol class="sl-visual" aria-label="Resumen del servicio"><?php foreach ($service['visual'] as $i => $item) : ?><li><span><?php echo esc_html(sprintf('%02d', $i + 1)); ?></span><strong><?php echo esc_html($item); ?></strong></li><?php endforeach; ?></ol><div class="sl-price"><strong>$200</strong><span>presencia digital inicial coordinada</span><a class="button primary" href="#que-incluye">Ver qué incluye</a></div></div>
  <aside class="sl-form" id="formulario"><p class="eyebrow">Hablemos de tu proyecto</p><h2><?php echo esc_html($service['form_title']); ?></h2><p><?php echo esc_html($service['form_intro']); ?></p><?php echo do_shortcode('[codepty_formulario_contacto]'); ?></aside>
  </div>
</div></section>
<section class="service-section"><div class="container service-reading"><p class="eyebrow">El beneficio</p><h2><?php echo esc_html($service['benefit_title']); ?></h2><p><?php echo esc_html($service['benefit']); ?></p><blockquote><?php echo esc_html($service['problem']); ?></blockquote></div></section>
<section class="service-section service-section--soft"><div class="container service-split"><div><p class="eyebrow">El problema que resolvemos</p><h2><?php echo esc_html($service['problem_title']); ?></h2><p><?php echo esc_html($service['problem']); ?></p></div><div><h3>Cómo lo hacemos</h3><ul class="service-checklist"><?php foreach ($service['specifics'] as $item) : ?><li><?php echo esc_html($item); ?></li><?php endforeach; ?></ul></div></div></section>
<?php if (!empty($service['note'])) : ?><section class="service-section service-section--dark"><div class="container service-reading"><p class="eyebrow">Elección transparente</p><h2><?php echo esc_html($service['note_title']); ?></h2><p><?php echo esc_html($service['note']); ?></p></div></section><?php endif; ?>
<section class="service-section" id="como-trabajamos"><div class="container"><header class="sl-heading"><p class="eyebrow">Un proceso claro</p><h2>Cómo trabajamos contigo</h2></header><ol class="sl-process"><li><span>1</span><h3>Conocemos</h3><p>Conversamos sobre el negocio, sus clientes, objetivos y materiales.</p></li><li><span>2</span><h3>Ordenamos</h3><p>Definimos contenido, prioridades, canales y alcance antes de producir.</p></li><li><span>3</span><h3>Preparamos</h3><p>Construimos una primera propuesta funcional y coherente.</p></li><li><span>4</span><h3>Revisas</h3><p>Compruebas datos, textos, imágenes, enlaces y presentación.</p></li><li><span>5</span><h3>Corregimos y entregamos</h3><p>Aplicamos lo acordado, probamos y preparamos la versión definitiva.</p></li></ol></div></section>
<section class="service-section service-section--soft"><div class="container service-split"><div><p class="eyebrow">Qué recibes</p><h2>Una entrega preparada para tu negocio</h2><ul class="service-checklist"><?php foreach ($service['receives'] as $item) : ?><li><?php echo esc_html($item); ?></li><?php endforeach; ?></ul></div><div><p class="eyebrow">Qué necesitamos de ti</p><h2>Información real y una revisión atenta</h2><ul class="service-checklist"><?php foreach ($service['needs'] as $item) : ?><li><?php echo esc_html($item); ?></li><?php endforeach; ?></ul></div></div></section>
<section class="service-section sl-package" id="que-incluye"><div class="container"><div class="sl-package__intro"><p class="eyebrow">El paquete inicial</p><h2>Qué incluye el servicio por $200</h2><p>Aplicamos este enfoque específico dentro de una presencia digital inicial coordinada para que el negocio pueda presentarse y recibir contactos desde varios canales.</p></div><div class="sl-package__grid"><article><span>01</span><h3>Página web profesional</h3><p>Diseño, estructura, contenido y contacto según el alcance acordado.</p></article><article><span>02</span><h3>Facebook para empresas</h3><p>Preparación inicial de la página profesional.</p></article><article><span>03</span><h3>Instagram para negocios</h3><p>Preparación inicial del perfil de empresa.</p></article><article><span>04</span><h3>Linktree</h3><p>Un punto de acceso a los destinos principales.</p></article><article><span>05</span><h3>WhatsApp Business</h3><p>Configuración inicial de la información comercial.</p></article></div><div class="sl-limits"><h3>Límites claros antes de empezar</h3><p>El paquete cubre la preparación inicial confirmada. Dominio, alojamiento, publicidad, gestión continuada, mantenimiento, producción fotográfica, identidad completa, funciones especiales y trabajos posteriores no se presuponen incluidos: si hacen falta, se definen y presupuestan por separado. Tus cuentas, dominio y alojamiento permanecen a tu nombre.</p></div></div></section>
<section class="service-section" id="preguntas-frecuentes"><div class="container faq-grid service-faq"><header class="faq-heading"><p class="eyebrow">Antes de decidir</p><h2>Preguntas frecuentes</h2><p class="subtitle">Respuestas concretas sobre esta página y el alcance del servicio.</p></header><div class="faq-list"><?php foreach ($service['faq'] as $faq) : ?><details><summary><?php echo esc_html($faq[0]); ?></summary><p><?php echo esc_html($faq[1]); ?></p></details><?php endforeach; ?></div></div></section>
<section class="closing service-closing"><div class="container"><div class="closing-box"><div><p class="eyebrow">Tu presencia digital por $200</p><h2>Cuéntanos qué necesita tu negocio</h2><p>Revisamos tu caso y confirmamos alcance, materiales y siguientes pasos antes de empezar.</p></div><div class="closing-actions"><a class="button light" href="#formulario">Ir al formulario</a></div></div></div></section>
</main><?php get_template_part('template-parts/site-footer'); wp_footer(); ?></body></html>
